### PR TITLE
ETDF dates

### PR DESCRIPTION
**Pull request by magdasalatka**
Hi @oschihin 

here is our suggestion for transforming dates. Can you try running it in your intranet setup?

### CODE REVIEW

**Comment by oschihin** [comment]
Hi @magdasalatka 

Thanks for the suggestion. I fixed to things, please correct if I'm wrong. 
I think I am at a loss as how to test it. Are these new steps part of materialise or publish? The latter is not yet working, connecting our pipeline to the public endpoint is to be done (by zazuko).

**Review by oschihin — COMMENTED** [review]
On building it, i came upon this issue (#9). Not directly linked. Easy to fix?

**Comment by magdasalatka** [comment]
The new code is executed in the publishing step. I wasn't aware that it is not working.
In that case, I suggest me and @ktk refactor the pipeline and try running it locally first. Once that is done, we woiuld ask you to integrate the code into your intranet setup.

**Comment by oschihin** [comment]
Sounds sensible. Let me know if you need anything.

**Comment by oschihin** [comment]
This has been done manually. Also, data first had to be cleaned. Short: It works now, thanks @magdasalatka

**Pull request closed without merging**
